### ISSUE TITLE
Unit Tests for retries and backoff

### ISSUE THREAD

**Issue by asadali214** [apimatic/unirest-php#15]
Addition of unit tests for following methods used in calculation of retry and backoff intervals

1. Request::getRetryWaitTime()
2. Request::getRetryAfterInSeconds()
3. Request::sleep()

Also try to add atleast one test to calculate total wait time while client retries multiple times in order to get a response, this will ensure that retries feature is working properly

**Comment by thehappybug** [comment]
Your implementation does not handle all 3 cases for ForceRetries. I've written about it here:
https://github.com/apimatic/apimatic-codegen/issues/731#issuecomment-1062834434
