### ISSUE TITLE
Check support for PHP 8 

### ISSUE THREAD

**Issue by thehappybug** [apimatic/unirest-php#8]
The Travis config does not list PHP 8 as the environment to test in.

I am wondering whether this library works okay in PHP 8. We should update the tests and the config and ensure PHP 8 compatibility without dropping support for the current support PHP versions.

**Comment by asadali214** [comment]
> I am wondering whether this library works okay in PHP 8. 

I have tested the unirest-php project after updating its travis.yml file by adding php 8.0 to the list, and I got the following 3 errors, which I think were pre-existing. Only new issue is with testGzip in php 8.0 environment we are unable to get 'Content-Encoding' array key 
![image](https://user-images.githubusercontent.com/26116671/119621734-e7f83880-be1f-11eb-87f8-5fe45ea4e858.png)

Other then that after reviewing the code I find out that we are using files as mixed type after setting it as boolean:
![image](https://user-images.githubusercontent.com/26116671/119622583-b764ce80-be20-11eb-9042-8cc095a53290.png)

**Comment by thehappybug** [comment]
> I have also tested the unirest-php project after updating its travis.yml file by adding php 8.0 to the list, and I got the following 3 errors, which I think were pre-existing. Only new issue is with testGzip in php 8.0 environment we are unable to get 'Content-Encoding' array key

As you can see from the [last test run](https://travis-ci.org/apimatic/unirest-php), the tests are passing on other versions of PHP. You will have to fix the errors for PHP 8.

~PS: We're supposed to move the tests off Travis and to GH Actions this month. Travis is shutting down.~ (it is done)

> Other then that after reviewing the code I find out that we are using files as mixed type after setting it as boolean:

I don't see the error here. This looks like valid PHP code and should run. Do you run an error at runtime? What is the error message?
